#!/usr/bin/php
<?php

//load our OAuth stuff
require_once('twitteroauth/twitteroauth.php');

//clear the terminal
echo exec('clear');

//our main twitter function
function tweettweet($thisMsg) {
	//set our keys
	$consumerKey = '';
	$consumerSecret = '';
	$oAuthToken = '';
	$oAuthSecret = '';
	//declare our tweet mech
	$tweet = new TwitterOAuth($consumerKey, $consumerSecret, $oAuthToken, $oAuthSecret);
	//echo nice sending msg
	echo "Sending...";
	//send a tweet
	$tweet->post('statuses/update', array('status' => $thisMsg));
	//echo confirmation msg	
	echo "Sent!\n";
}

//Function to check the length of tweet.
function checkLen($thisMsg){
	$checkLen = strlen($thisMsg);
	
	if($checkLen > 141) { 
		echo "Your tweet exceeds the 140 char limit.\n";
		exit();
		}
}

function helpMsg() {
	echo "+++++++++++CLItweet PHP+++++++++\n";
	echo "+Command Line Interface tweet+++\n";
	echo "+Authered by james@jamesbos.com+\n";
	echo "+Licensed under GPLv2+         +\n";
	echo "++++++++++++++++++++++++++++++++\n";
	echo "usage:\n\n"; 
	echo "clitweet -s [your text] (send directly from CLI)\n";
	echo "         -h (help message you're looking at!)\n";
	echo "         -U (send your PC uptime)\n";
	echo "         -D (send your dist info eg. uname -a)\n\n";
	echo "Hot Tip:\n";
	echo "Remeber to use escape characters when using qoutes\n"; 
	echo "and other special chars eg. \' \& etc.\n\n";
	echo "You can also also enclose your entire tweet around\n";
	echo "double qoutes.\n\n"; 
}

$tweetText = $_SERVER['argv'];

function getString($tweetText)
        {
        $outval = "";
        foreach ($tweetText as $k=>$v)
                {
                if (2 > $k) continue; 
                if(is_array($v)) 
                {
                        $outval .= makestring($v);
                }
        else 
                {
                        $outval .= "$v ";
                }
        } 
return $outval;
}

//define var as our function to get CLI input
$cliMsg = getString($tweetText);

//confirm that length does not exceed 140char limit
$cliMsg = checkLen($cliMsg);

/*
Define our bash functions we want to parse to twitter (this will get bigger)
*/
$tweetUptime = exec('uptime');

/*Turn off errors at last minute if someone enters no arguement when entering command, hense
why it is left to the last minute. Lazy, I know... must be a better solution.*/
error_reporting(0);
//declare our command line arguments
$option = $_SERVER['argv'][1];
	if (empty($option)) {echo "Please use -h to get a list of options"; }
	if ($option == '-h') { helpMsg(); exit(); } 
	if ($option == '-s') { tweettweet($cliMsg); exit(); }
	if ($option == '-U') { tweettweet($tweetUptime); exit(); }
?>

